name = "Taped"
uuid = "07d77754-e150-4737-8c94-cd238a1fb45b"
authors = ["Will Tebbutt and contributors"]
version = "1.0.0-DEV"

[deps]
Umlaut = "92992a2b-8ce5-4a9c-bb9d-58be9a7dc841"

[compat]
ReverseDiff = "1"
Umlaut = "0.5"
julia = "1"

[extras]
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ReverseDiff", "Test"]
